### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by dvberkel** [HAN-ASD-DT/rsa-assignment-Dewinster#2]
your `repeat` function is not really a repeat, more like a `map`. This function can also be found in the [core](https://package.elm-lang.org/packages/elm/core/latest/List#map) library

**Comment by Dewinster** [comment]
Solved by renaming the function: [Reference](https://github.com/HAN-ASD-DT/rsa-assignment-Dewinster/commit/eed25fe6a308e07ecf2e84df451da76be0886a8f)
